name = "zerotalk"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
APP_ORIGIN = "https://maitononaka.github.io"
APP_URL = "https://maitononaka.github.io/ZeroTalk/"
GOOGLE_CLIENT_ID = "REPLACE_ME.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "https://zerotalk.maitomandeluxe.workers.dev/api/auth/google/callback"

[[d1_databases]]
binding = "DB"
database_name = "zerochat_db"
database_id = "8d8ff79d-dd88-4a98-b939-ce9f0d04a01f"

[triggers]
crons = ["*/15 * * * *"]